# Generated by Django 2.0.4 on 2018-06-01 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('token', models.CharField(default=uuid.UUID('a6f0fedd-4211-4e1b-aee2-8b587cbeebcc'), max_length=500)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
