# Generated by Django 2.0.6 on 2018-06-29 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180629_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.UUID('28922a26-8509-4387-9587-7224e674af33'), max_length=500),
        ),
    ]
