# Generated by Django 2.0.4 on 2018-04-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle_text', models.CharField(max_length=500)),
                ('answer_text', models.CharField(max_length=500)),
                ('clarifai_model', models.CharField(default='general-v1.3', max_length=100)),
            ],
        ),
    ]
