# Generated by Django 2.0.4 on 2018-04-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_runningchallenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningchallenges',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Site', unique=True),
        ),
    ]
