# Generated by Django 2.0.6 on 2018-06-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20180601_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningchallenges',
            name='site',
        ),
    ]
