# Generated by Django 2.0.6 on 2018-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_classes_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='times_fail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='times_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='times_tried',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
