# Generated by Django 2.0.6 on 2018-07-01 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20180630_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='times_fail',
            new_name='times_failed',
        ),
        migrations.AddField(
            model_name='challenge',
            name='last_failed',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='challenge',
            name='last_solved',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='challenge',
            name='last_tried',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
