# Generated by Django 2.0.6 on 2018-07-01 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20180701_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=500)),
                ('success', models.BooleanField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trials', to='challenges.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='runningchallenges',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runningchallenges',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='runningchallenges',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='running_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trials', to='challenges.RunningChallenges'),
        ),
    ]
