# Generated by Django 2.0.6 on 2018-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20180701_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningchallenges',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
