# Generated by Django 2.0.6 on 2018-07-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_trial_trial_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='player_pseudo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
