# Generated by Django 2.0.6 on 2018-07-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_trial_player_pseudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_pseudo', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
