# Generated by Django 2.0.6 on 2018-07-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='classes',
            field=models.CharField(max_length=5000),
        ),
    ]
