# Generated by Django 2.0.6 on 2018-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20180704_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='player_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_pseudo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trial',
            name='player_pseudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
